# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 2, 15, 21, 14, 4, 795639, tzinfo=utc)),
        ),
    ]
